services:
  - type: web
    name: SecretSantaMysteryBot
    runtime: python
    env: production
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        generateValue: true