services:
  - type: worker
    name: secret-santa-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    # Worker сервис не требует портов - только background процесс
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false